services:
  - type: web
    name: llm-inference-api
    env: docker     # ✅ Correct way to signal Docker usage
    plan: free
    repo: https://github.com/chiefnarx/LLM_Inference_System
    branch: main
    autoDeploy: true